.DEFAULT_GOAL := help

PORT = 8880

# ── Help ──────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo ""
	@echo "  make serve    Start dev server → http://localhost:$(PORT)"
	@echo "  make kill     Kill this project's HTTP server"
	@echo "  make validate Run every validator. Required before any data/ change lands."
	@echo ""

# ── Dev server ────────────────────────────────────────────────────────────────
# scripts/serve.py is http.server plus Cache-Control: no-cache; a plain
# http.server sends only Last-Modified, so browsers keep stale ES modules after
# edits. Falls back to plain http.server outside the monorepo.
.PHONY: serve
serve:
	@echo "Serving → http://localhost:$(PORT)"
	@if [ -f ../../scripts/serve.py ]; then python3 ../../scripts/serve.py $(PORT); else python3 -m http.server $(PORT); fi

# ── Kill ──────────────────────────────────────────────────────────────────────
.PHONY: kill
kill:
	@lsof -ti :$(PORT) | xargs kill 2>/dev/null && echo "Stopped server on port $(PORT)" || echo "No server running on port $(PORT)"

# ── Validate ──────────────────────────────────────────────────────────────────
# Node with no dependencies, so there is no install step. Each one exits 0, or
# exits 1 naming the file, the item and the field.
#
# One target per validator. To wire in another one, add a .PHONY target and a
# bare `validate: <your-target>` line of your own: make collects prerequisites
# from every rule for a target as long as only one of them carries a recipe, so
# two workstreams can each add a validator without editing the other's line.
.PHONY: validate
validate: validate-sets
	@echo "validate: every check passed"

# neo-quiz-set/1 and neo-quiz-set-index/1: every set under data/sets, then the
# index against the files it names. The sets are generated by
# runcible-site/tools/build-sets.mjs; see data/README.md.
.PHONY: validate-sets
validate-sets:
	@node tools/validate-set.mjs
